name: Build and Push Neovim Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - repo_name: kickstart.nvim
            repo_url: https://github.com/nvim-lua/kickstart.nvim
            plugin_manager: lazy
            base_image: ubuntu:24.04
          - repo_name: kickstart.nvim
            repo_url: https://github.com/nvim-lua/kickstart.nvim
            plugin_manager: lazy
            base_image: alpine:3.20

          - repo_name: lazyvim
            repo_url: https://github.com/LazyVim/starter
            plugin_manager: lazy
            base_image: ubuntu:24.04
          - repo_name: lazyvim
            repo_url: https://github.com/LazyVim/starter
            plugin_manager: lazy
            base_image: alpine:3.20

          - repo_name: nvchad
            repo_url: https://github.com/NvChad/starter
            plugin_manager: packer
            base_image: ubuntu:24.04
          - repo_name: nvchad
            repo_url: https://github.com/NvChad/starter
            plugin_manager: packer
            base_image: alpine:3.20

          - repo_name: astronvim
            repo_url: https://github.com/AstroNvim/template
            plugin_manager: lazy
            base_image: ubuntu:24.04
          - repo_name: astronvim
            repo_url: https://github.com/AstroNvim/template
            plugin_manager: lazy
            base_image: alpine:3.20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/neovim:${{ matrix.repo_name }}-${{ matrix.base_image//[:\/]/- }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            NVIM_CONFIG_REPO_URL=${{ matrix.repo_url }}
            NVIM_PLUGIN_MANAGER=${{ matrix.plugin_manager }}

      - name: Output Image Digest
        run: |
          echo "Built and pushed image ghcr.io/${{ github.repository_owner }}/neovim:${{ matrix.repo_name }}-${{ matrix.base_image//[:\/]/- }}"
